### ISSUE TITLE
希望添加剪切板功能，现在不能复制粘贴。

### ISSUE THREAD

**Issue by dukewan** [sapjax/fewords#1]
feword很漂亮！很好用。

1.希望添加剪切板功能，现在不能复制粘贴。
2.添加markdown支持

主要用来记录一些工具的链接信息，复制粘贴很重要。

**Comment by sapjax** [comment]
@dukewan 
1. 我本地开发的时候是支持剪贴板操作的，不知道为什么打包之后的程序不支持了，我查一下，可能是个bug
2. 现在是支持markdown的啊

**Comment by sapjax** [comment]
@dukewan 复制/粘贴的问题已经解决，可以下载新版本v002试试 http://pan.baidu.com/s/1eQjVu2A#path=%252Ffewords

**Comment by dukewan** [comment]
@sapjax 多谢！可以复制粘贴了。快捷键的设置怪怪的, 不支持组合键嘛？

**Comment by sapjax** [comment]
@dukewan  支持组合键啊，同时按下就可以了，组合键必须有一个是特殊的键位(`command`, `shift`, `ctrl`, `alt`)其中一个。

**Comment by dukewan** [comment]
@sapjax 原来如此，我说怎么单独按键没有反应。: )

**Comment by sapjax** [comment]
@dukewan  单独按键应该也是有反应的，之前的版本还是有个bug :sob: 。
[新版本](http://pan.baidu.com/s/1qWtKzLi) 修复了。

重新安装的话，最好删除配置文件 `rm ~/.fewords-config.json`
另外存储目录的设定改了一下，现在是直接存到设置的目录，之前会多一个`fewords`目录。

**Comment by dukewan** [comment]
@sapjax 好的！现在已经很完美啦！
